### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Rebelgotnochill** [hernandoagf/price-bot-coingecko#1]

**Comment by hernandoagf** [comment]
Hi! Are you getting any error? It's working on my end.

**Comment by Rebelgotnochill** [comment]
i depolyed it on heroku and addded all settings needed but it not showing me price on discord of selected coingecko token. it cpoming online going offline after some time

**Comment by hernandoagf** [comment]
If you go to Heroku logs, does it show an error? Also, you need to turn off the web dyno on Heroku and turn on the worker one:

![image](https://user-images.githubusercontent.com/22449631/116107028-06d0a700-a689-11eb-9b76-dd2d0129be7a.png)

**Comment by Rebelgotnochill** [comment]
its working now thanks
and also can you make a bot for stocks

**Comment by hernandoagf** [comment]
Glad it worked!

Hmm, a bot for stocks should be very different than this one, it just needs a place where it can fetch the data from. But I'm not very familiar with stocks 😅

**Comment by Rebelgotnochill** [comment]
you can use nasdaq to get data
